config/routes.rb
Rails.application.routes.draw do
  resources :detail_kasbons
  resources :potongan_employees
  resources :kasbons
  resources :potongans
  resources :golongans
  resources :take_homes
  resources :additional_incomes
  resources :salaries
  resources :attendances
  resources :group_rosters
  resources :rosters
  resources :restos
  resources :position_groups
  resources :locations
  resources :employees

  root 'welcome#index'
  get 'restos/:id/new' => 'restos#add_employee', as: :add_employee
  get 'employees/salary_recap/:month&:year' => 'employees#salary_recap', as: :salary_recap
  get 'golongans/:id/group_rosters' => 'golongans#roster_group', as: :roster_group
  get 'employees/:id/salary_detail/:month&:year' =>'employees#salary_detail', as: :salary_detail
  get 'employees/:id/tambah_income/:month&:year' =>'employees#tambah_income', as: :tambah_income
  get 'employees/:id/kasbon' => 'employees#kasbon', as: :employee_kasbon
  post 'employees/:id/add_row/:month&:year' => 'employees#add_row', as: :emp_add_income_row
  post 'employees/:id/add_potong/:month&:year' => 'employees#add_potong', as: :emp_add_potong_row
  

end

app/models/employee.rb
class Employee < ActiveRecord::Base
    has_many :restos
    has_many :position_groups, through: :restos
    has_many :additional_incomes
    has_many :potongan_employees
    has_many :kasbons
    has_many :detail_kasbons, through: :kasbons
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy, :salary_detail, :tambah_income, :add_potong, :kasbon]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all.order(:name)
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

 
  def salary_recap
  
   Attendance.generate_attendance_form(Date.parse(params[:year]+ "-" + params[:month] + "-1"))
   Attendance.calculate_take_home(Date.parse(params[:year]+ "-" + params[:month] + "-1"))
   @attendances = Employee.joins('left join restos on restos.employee_id = employees.id')
   .joins('left join position_groups on position_groups.id = restos.position_group_id')
   .joins('left join golongans on golongans.id = position_groups.golongan_id')
   .joins('left join take_homes on take_homes.employee_id = employees.id')
   .joins('left join locations on locations.id = restos.location_id')
   .select('golongans.*','employees.*','locations.name as location', 'take_homes.salary','take_homes.add_income','take_homes.sal_cut')
   .where('take_homes.pay_month = ?', Date.parse(params[:year]+"-"+params[:month]+"-1"))

  end  
  
  def salary_detail
    #@pots = PotonganEmployee.where('employee_id = ?', @employee)
    PotonganEmployee.update_amount_kasbon(@employee,params[:month],params[:year])
    @atts = Attendance.where('attendances.employee_id = ? AND attendances.att_month = ?', @employee, Date.parse(params[:year]+ "-" + params[:month] + "-1"))
            .joins('left join group_rosters on group_rosters.id = attendances.group_roster_id')
            .joins('left join rosters on rosters.id = group_rosters.roster_id').all
    @total_hadir = 0      
    @atts.each do |att|
      if att.group_roster.roster.tipe == "Minus"
        @total_hadir = @total_hadir - (att.group_roster.amount * att.day_count) 
      else
        @total_hadir = @total_hadir + (att.group_roster.amount * att.day_count)
      end
    end
    @additions = AdditionalIncome.where('employee_id=? and add_month = ?', @employee, Date.parse(params[:year]+ "-" + params[:month] + "-1"))        
    @total_add = 0
    @additions.each do |add|
      @total_add = @total_add + add.amount
    end
    
    @pots = PotonganEmployee.where('potongan_employees.employee_id=? and pot_month = ?', @employee, Date.parse(params[:year]+ "-" + params[:month] + "-1"))        
            .joins('left outer join kasbons on kasbons.id = potongan_employees.kasbon_id')
            .select('potongan_employees.*', 'kasbons.nama as kasbonname')
    @kasbon = Kasbon.where('employee_id = ? and sisa > ?', @employee, 0).first
    @total_pot = 0
    @pots.each do |pot|
      @total_pot = @total_pot + pot.amount
    end
    
    @total = @total_hadir + @total_add - @total_pot
    
    
    
  end
  
  def tambah_income
    @additional_income = AdditionalIncome.new
  end
  def add_row
    AdditionalIncome.add_row_income(params[:id],params[:month],params[:year])
    redirect_to :back
  end
  def add_potong
    PotonganEmployee.add_row_potong(params[:id],params[:month],params[:year])
    redirect_to :back
  end
  
  def kasbon
    @kasbons = Kasbon.where('employee_id = ?', @employee)
  end
  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :phone, :email, :acc_no, :pob, :dob, :work_started, :work_end, :gp, :golongan)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_add_payment.html.erb
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-lg-5">
        <h3 style="margin-bottom: 30px; margin-top: 0px;">Tambahan (Rp. <%= @total_add.nil? ? 0 : delimiter(@total_add) %>)</h3>
      </div>
      <div class="col-lg-7">
        <%= link_to 'Tambah Income', emp_add_income_row_path, method: :post, class: 'btn btn-primary pull-right' %>
      </div>
    </div>
    
    <div class="row">
      <div class="col-lg-12">
        <div class="table-responsive">
          <table class="table table-bordered table-hover table-condensed">
            <thead>
              <tr>
                <th>Keterangan</th>
                <th>Jumlah</th>
                <th>Action</th>
              </tr>
            </thead>
          
            <tbody>
              <% @additions.each do |add| %>
                <tr>
                  <td><%= best_in_place add, :name %></td>
                  <td><%= best_in_place add, :amount, class:"pull-right" %></td>
                  <td class="center">
                    <%= link_to  add, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
                            <i class="glyphicon glyphicon-trash"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/_att_payment.html.erb
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-lg-12">
        <h3 style="margin-bottom: 30px; margin-top: 0px;">Kehadiran (Rp. <%= @total_hadir.nil? ? 0 : delimiter(@total_hadir) %>)</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="table-responsive">
          <table class="table table-bordered table-hover table-condensed">
            <thead>
              <tr>
                <th>Hari Kerja</th>
                <th>Nilai</th>
                <th>Jumlah Hari</th>
                <th>Total</th>
              </tr>
            </thead>
          
            <tbody>
              <% @atts.each do |attendance| %>
                <% if attendance.group_roster.roster.tipe == "Minus" %>
                  <tr style="background-color: #D98880;">
                <% else %>
                  <tr>
                <% end %>
                  <td>
                      <%= attendance.group_roster.roster.hari %>
                      <%= attendance.group_roster.roster.detail %>
                  </td>
                  <td style="text-align: right;"><%= delimiter(attendance.group_roster.amount) %></td>
                  <td style="text-align: right;"><%= best_in_place attendance, :day_count %></td>
                  <td style="text-align: right;">
                    <% if attendance.group_roster.roster.tipe == "Plus" %>
                      <%= delimiter(attendance.day_count * attendance.group_roster.amount) %>
                    <% else %>
                      <%= delimiter(attendance.day_count * attendance.group_roster.amount * -1) %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/_employee_list.html.erb
<h1>Employee List of Resto</h1>
<div class="table-responsive">
  <table class="table table-bordered table-hover table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Posisi</th>
        <th>Sejak</th>
        <th>Hingga</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
  
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.name %></td>
          <td><%= employee.phone %></td>
          <td><%= employee.email %></td>
          <td><%= employee.acc_no %></td>
          <td><%= employee.pob %></td>
          <td><%= employee.dob %></td>
          <td><%= employee.work_started %></td>
          <td><%= employee.work_end %></td>
          <td align="center", width="15%">
            <%= link_to  employee  , class: 'btn btn-info' do %>
              <i class="glyphicon glyphicon-eye-open"></i>
            <% end %>
            <%= link_to edit_employee_path(employee), class: 'btn btn-success' do%>
              <i class="glyphicon glyphicon-edit"></i>
            <% end %>
            <%= link_to  employee, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
              <i class="glyphicon glyphicon-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %> :
    <%= f.text_field :name, class:"form-control" %>
  </div>
    
  <div class="form-group">
    <%= f.label :phone %> :
    <%= f.text_field :phone, class:"form-control", placeholder:"Nomor telepon" %>
  </div>
    
  <div class="form-group">  
    <%= f.label :email %> :
    <%= f.text_field :email, class:"form-control", placeholder:"Alamat email" %>
  </div>
    
  <div class="field">
    <%= f.label :acc_no %> :
    <%= f.text_field :acc_no, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :gp %> :
    <%= f.text_field :gp, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :golongan %> :
    <%= f.text_field :golongan, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :pob %> :
    <%= f.text_field :pob, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_select :dob, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :work_started %><br>
    <%= f.date_select :work_started, class:"form-control" %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/_pot_payment.html.erb
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-lg-5">
        <h3 style="margin-bottom: 30px; margin-top: 0px;">Potongan (Rp. <%= delimiter(@total_pot) %>)</h3>
      </div>
      <div class="col-lg-7">
        <%= link_to 'Potongan', emp_add_potong_row_path, method: :post, class: 'btn btn-primary pull-right' %>
      </div>
    </div>
    
    <div class="row">
      <div class="col-lg-12">
        <div class="table-responsive">
          <table class="table table-bordered table-hover table-condensed">
            <thead>
              <tr>
                <th>Keterangan</th>
                <th>Detail</th>
                <th>Jumlah</th>
                <th>Action</th>
              </tr>
            </thead>
          
            <tbody>
               <% @pots.each do |pot| %>
                   <tr>
                       <td>
                         <% if pot.nama_potongan == "Kasbon" %>
                           <% if @kasbon.nil? == true %>
                             <%= link_to pot.nama_potongan, new_kasbon_path %>
                           <% else %>
                             <%= link_to pot.nama_potongan, kasbon_path(@kasbon.id) %>
                           <% end %>
                         <% else %>
                           <%= best_in_place pot, :nama_potongan %>
                         <% end %>
                       </td>
                       <td>
                           <% if pot.nama_potongan == "Kasbon" %>
                             <%= best_in_place pot, :kasbon_id, :as => :select, :collection => Kasbon.kasbon_to_hash(@employee) %>
                           <% end %>
                       </td>
                       <td style="text-align: right;">
                         <% if pot.kasbon.present? %>
                           <%= delimiter(pot.amount) %>
                         <% else %>
                           <%= best_in_place pot, :amount, :display_with => :number_with_delimiter %>
                         <% end %>
                       </td>
                       <td class="center">
                          <%= link_to  pot, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
                                  <i class="glyphicon glyphicon-trash"></i>
                          <% end %>
                       </td>
                   </tr>
               <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/edit.html.erb
<div class="container">
  <nav class="navbar navbar-inverse">
    <p class="navbar-title">Edit Karyawan</p>
  </nav>
</div><br>
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-lg-12">

            <%= render 'form' %>
            
            <%= link_to 'Show', @employee %> |
            <%= link_to 'Back', employees_path %>
       </div>
    </div>
  </div>
</div>

app/views/employees/index.html.erb
<div class="container">
  <nav class="navbar navbar-inverse">
    <p class="navbar-title">Employees Listing</p>
  </nav>
</div><br>
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-lg-12">
          
          <div class="row">
            <%= link_to 'Tambah Karyawan', new_employee_path, class: 'btn btn-primary pull-right' %>
          </div><br>
          <div class="row">
            <div class="table-responsive">
              <table class="table table-bordered table-hover table-condensed">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Acc no</th>
                    <th>GP</th>
                    <th>Gol.</th>
                    <th>Pob</th>
                    <th>Dob</th>
                    <th>Work started</th>
                    <th>Work end</th>
                    <th colspan="3">Actions</th>
                  </tr>
                </thead>
              
                <tbody>
                  <% @employees.each do |employee| %>
                    <tr>
                      <td><%= employee.name %></td>
                      <td><%= employee.phone %></td>
                      <td><%= employee.email %></td>
                      <td><%= employee.acc_no %></td>
                      <td><%= number_with_delimiter(employee.gp) %></td>
                      <td><%= employee.golongan %></td>
                      <td><%= employee.pob %></td>
                      <td><%= employee.dob %></td>
                      <td><%= employee.work_started %></td>
                      <td><%= employee.work_end %></td>
                      <td align="center", width="15%">
                        <%= link_to  employee  , class: 'btn btn-info' do %>
                          <i class="glyphicon glyphicon-eye-open"></i>
                        <% end %>
                        <%= link_to edit_employee_path(employee), class: 'btn btn-success' do%>
                          <i class="glyphicon glyphicon-edit"></i>
                        <% end %>
                        <%= link_to  employee, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
                          <i class="glyphicon glyphicon-trash"></i>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
       </div>
    </div>
  </div>
</div>

app/views/employees/kasbon.html.erb
<div class="container">
  <nav class="navbar navbar-inverse">
    <p class="navbar-title">Pinjaman Karyawan</p>
  </nav>
</div><br>
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-lg-12">
          
          <div class="row">
            <%= link_to 'Tambah Pinjaman', new_employee_path, class: 'btn btn-primary pull-right' %>
          </div><br>
          <div class="row">
            <div class="table-responsive">
              <table class="table table-bordered table-hover table-condensed">
                <thead>
                  <tr>
                    <th>Keterangan</th>
                    <th>Tanggal Pinjaman</th>
                    <th>Jumlah Pinjaman</th>
                    <th>Tanggal Bayar Terakhir</th>
                    <th>Jumlah Bayar Terakhir</th>
                    <th>Sisa</th>
                    <th colspan="3">Actions</th>
                  </tr>
                </thead>
              
                <tbody>
                  <% @kasbons.each do |kasbon| %>
                    <tr>
                      <td><%= kasbon.nama %></td>
                      <td><%= kasbon.tanggal_pinjam %></td>
                      <td><%= delimiter(kasbon.jumlah_pinjam) %></td>
                      <td><%= kasbon.tanggal_bayar %></td>
                      <td><%= delimiter(kasbon.jumlah_bayar) %></td>
                      <td><%= delimiter(kasbon.sisa) %></td>
                      <td>
                        <%= link_to  kasbon, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
                          <i class="glyphicon glyphicon-trash"></i>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
       </div>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<div class="container">
  <nav class="navbar navbar-inverse">
    <div class="navbar-title-arrow">
      <p><%= link_to employees_path do %></p>
          <i class="glyphicon glyphicon-chevron-left"></i>
      <% end %>
      Tambah Karyawan
    </div>
  </nav>
</div><br>
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-lg-12">
        <%= render 'form' %>
      
       </div>
    </div>
  </div>
</div>

app/views/employees/salary_detail.html.erb
<div class="container">
  <nav class="navbar navbar-inverse">
    <div class="navbar-title-arrow">
        <p><%= link_to salary_recap_path(params[:month],params[:year]) do %></p>
               <i class="glyphicon glyphicon-chevron-left"></i>
           <% end %>
           <%= @employee.name %>
           <p class="navbar-title-arrow pull-right" style="margin-right: 20px;">Rp. <%= @total.nil? ? 0 : delimiter(@total) %></p>
    </div>
  </nav>
</div><br>
<%= render 'att_payment' %>
<%= render 'add_payment' %>
<%= render 'pot_payment' %>
    

app/views/employees/salary_recap.html.erb
<div class="container">
  <nav class="navbar navbar-inverse">
    <p class="navbar-title" style="margin-top: 20px;">Rekap Gaji <%= (Date.parse(params[:year]+"-"+params[:month]+"-1")).strftime("%B %Y") %></p>
    <p class="pull-right" style="margin-top: 10px; margin-right: 20px;">
         <%= select_tag 'select_path', options_for_select((1..12).map {|m| [Date::MONTHNAMES[m], m]}),:prompt => "Pilih Bulan" %>
         <%= select_tag 'tahun', options_for_select((Date.today.year-5)..(Date.today.year+1)),:prompt => "Pilih Tahun" %>
         <button type="button" id="myBtn" class="btn btn-primary" style="margin-bottom: 5px;">Refresh</button>
    </p>
    <p style='margin-top: 20px; margin-right: 10px', class="navbar-title-arrow pull-right">
      Periode :
    </p>
  </nav>
</div><br>
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-lg-12">
        <div class="row">
          <div class="col-lg-2" style="margin-top: 10px;">
            <p>Filter tabel: </p>
          </div>
          <div class="col-lg-10">
            <p><input class="form-control" id="myInput" type="text" placeholder="Masukan kata yang dicari"></p>
          </div>
        </div>
        <div class="table-responsive">
          <table class="table table-bordered table-hover table-condensed">
            <thead>
              <tr>
                <th>Lokasi</th>
                <th>Nama</th>
                <!--<th>Mulai Kerja</th>-->
                <th>No. Rek</th>
                <th>Golongan</th>
                <th>Gaji Pokok</th>
                <th>Kehadiran</th>
                <th>Total Gaji</th>
                <th>Tambahan</th>
                <th>Total</th>
                <th>Potongan</th>
                <th>Take Home</th>
                <th>Detail</th>
                
              </tr>
            </thead>
          
            <tbody id="myTable">
              
              <% @attendances.each do |att| %>
              <tr>
                <td><%= att.location %> </td>
                <td><%= link_to att.name, salary_detail_path(att.id,params[:month],params[:year]) %> </td>
                <!--<td>%= att.work_started %></td>-->
                <td><%= att.acc_no %></td>
                <td><%= att.golongan %></td>
                <td><%= att.gp.nil? ? "0" : delimiter(att.gp) %> </td>
                <td><%= att.salary.nil? ? "0" : delimiter(att.salary) %> </td>
                <td><%= delimiter((att.salary.nil? ? 0 : att.salary) + (att.gp.nil? ? 0 : att.gp.to_d)) %> </td>
                <td><%= att.add_income.nil? ? 0 : delimiter(att.add_income) %> </td>
                <td><%= delimiter((att.salary.nil? ? 0 : att.salary) + (att.gp.nil? ? 0 : att.gp.to_d) + (att.add_income.nil? ? 0 : att.add_income)) %> </td>
                <td><%= att.sal_cut.nil? ? "0" : delimiter(att.sal_cut) %> </td>
                <td><%= delimiter((att.salary.nil? ? 0 : att.salary) + (att.gp.nil? ? 0 : att.gp.to_d) + (att.add_income.nil? ? 0 : att.add_income) - (att.sal_cut.nil? ? 0 : att.sal_cut)) %> </td>
                <td align="center">
                    <%= link_to  salary_detail_path(att.id,params[:month],params[:year])  , class: 'btn btn-info' do %>
                      <i class="glyphicon glyphicon-eye-open"></i>
                    <% end %>
                </td>
              </tr>
              <% end %>
              
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  document.getElementById("myBtn").onclick = function() {myFunction()};
    function myFunction() {
    var selected = document.getElementById('select_path').value;
    var thn = document.getElementById('tahun').value;
    var url = "/employees/salary_recap/" + selected + "&" + thn
          if (url) {
              window.location.replace(url);
          }
          return false;
  }


  $(document).ready(function(){
    $("#myInput").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#myTable tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
      });
    });
  });    
</script>

app/views/employees/show.html.erb
<div class="container">
  <nav class="navbar navbar-inverse">
    <p class="navbar-title"><%= @employee.name %></p>
  </nav>
</div><br>
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-lg-12">

        <p>
          <strong>Name:</strong>
          <%= best_in_place @employee, :name %>
        </p>
        
        <p>
          <strong>Phone:</strong>
          <%= @employee.phone %>
        </p>
        
        <p>
          <strong>Email:</strong>
          <%= @employee.email %>
        </p>
        
        <p>
          <strong>Acc no:</strong>
          <%= @employee.acc_no %>
        </p>
        
        <p>
          <strong>Gaji Pokok:</strong>
          <%= @employee.gp.nil? ? 0 : delimiter(@employee.gp) %>
        </p>
        
        <p>
          <strong>Golongan:</strong>
          <%= @employee.golongan.nil? ? "-" : @employee.golongan %>
        </p>
        
        <p>
          <strong>Pob:</strong>
          <%= @employee.pob %>
        </p>
        
        <p>
          <strong>Dob:</strong>
          <%= @employee.dob %>
        </p>
        
        <p>
          <strong>Work started:</strong>
          <%= @employee.work_started %>
        </p>
        
        <p>
          <strong>Work end:</strong>
          <%= @employee.work_end %>
        </p>
        
        <%= link_to 'Edit', edit_employee_path(@employee) %> |
        <%= link_to 'Back', employees_path %>
       </div>
    </div>
  </div>
</div>

app/views/employees/tambah_income.html.erb
<div class="container">
  <nav class="navbar navbar-inverse">
    <p><%= link_to "back", salary_detail_path(params[:id],params[:month],params[:year]) %></p>
    <p class="navbar-title">Tambahan (<%= @employee.name %>)</p>
  </nav>
</div><br>
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-lg-12">
        <%= form_for(@additional_income) do |f| %>
          <% if @additional_income.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@additional_income.errors.count, "error") %> prohibited this additional_income from being saved:</h2>
        
              <ul>
              <% @additional_income.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
        
          <div class="field">
            <%= f.hidden_field :add_month, :value => Date.parse(params[:year]+ "-" + params[:month] + "-1") %>
          </div>
          <div class="field">
            <%= f.label :Keterangan %><br>
            <%= f.text_field :name %>
          </div>
          <div class="field">
            <%= f.label :Jumlah %><br>
            <%= f.text_field :amount %>
          </div>
          <div class="field">
            <%= f.hidden_field :employee_id, :value => params[:id] %>
          </div>
          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>