config/routes.rb
Rails.application.routes.draw do
  resources :detail_kasbons
  resources :potongan_employees
  resources :kasbons
  resources :potongans
  resources :golongans
  resources :take_homes
  resources :additional_incomes
  resources :salaries
  resources :attendances
  resources :group_rosters
  resources :rosters
  resources :restos
  resources :position_groups
  resources :locations
  resources :employees

  root 'welcome#index'
  get 'restos/:id/new' => 'restos#add_employee', as: :add_employee
  get 'employees/salary_recap/:month&:year' => 'employees#salary_recap', as: :salary_recap
  get 'golongans/:id/group_rosters' => 'golongans#roster_group', as: :roster_group
  get 'employees/:id/salary_detail/:month&:year' =>'employees#salary_detail', as: :salary_detail
  get 'employees/:id/tambah_income/:month&:year' =>'employees#tambah_income', as: :tambah_income
  get 'employees/:id/kasbon' => 'employees#kasbon', as: :employee_kasbon
  post 'employees/:id/add_row/:month&:year' => 'employees#add_row', as: :emp_add_income_row
  post 'employees/:id/add_potong/:month&:year' => 'employees#add_potong', as: :emp_add_potong_row
  

end

app/models/detail_kasbon.rb
class DetailKasbon < ActiveRecord::Base
    belongs_to :kasbon
end

app/controllers/detail_kasbons_controller.rb
class DetailKasbonsController < ApplicationController
  before_action :set_detail_kasbon, only: [:show, :edit, :update, :destroy]

  # GET /detail_kasbons
  # GET /detail_kasbons.json
  def index
    @detail_kasbons = DetailKasbon.all
  end

  # GET /detail_kasbons/1
  # GET /detail_kasbons/1.json
  def show
  end

  # GET /detail_kasbons/new
  def new
    @detail_kasbon = DetailKasbon.new
  end

  # GET /detail_kasbons/1/edit
  def edit
  end

  # POST /detail_kasbons
  # POST /detail_kasbons.json
  def create
    @detail_kasbon = DetailKasbon.new(detail_kasbon_params)

    respond_to do |format|
      if @detail_kasbon.save
        Kasbon.sum_sisa
        format.html { redirect_to :back, notice: 'Detail kasbon was successfully created.' }
        format.json { render :show, status: :created, location: @detail_kasbon }
      else
        format.html { render :new }
        format.json { render json: @detail_kasbon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /detail_kasbons/1
  # PATCH/PUT /detail_kasbons/1.json
  def update
    respond_to do |format|
      if @detail_kasbon.update(detail_kasbon_params)
        format.html { redirect_to @detail_kasbon, notice: 'Detail kasbon was successfully updated.' }
        format.json { render :show, status: :ok, location: @detail_kasbon }
      else
        format.html { render :edit }
        format.json { render json: @detail_kasbon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detail_kasbons/1
  # DELETE /detail_kasbons/1.json
  def destroy
    @detail_kasbon.destroy
    Kasbon.sum_sisa
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Detail kasbon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail_kasbon
      @detail_kasbon = DetailKasbon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detail_kasbon_params
      params.require(:detail_kasbon).permit(:kasbon_id, :tanggal_bayar, :jumlah_bayar, :sisa)
    end
end

app/helpers/detail_kasbons_helper.rb
module DetailKasbonsHelper
end

app/views/detail_kasbons/_form.html.erb
<%= form_for(@detail_kasbon) do |f| %>
  <% if @detail_kasbon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@detail_kasbon.errors.count, "error") %> prohibited this detail_kasbon from being saved:</h2>

      <ul>
      <% @detail_kasbon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tanggal_bayar %><br>
    <%= f.date_select(:tanggal_bayar, discard_day: true, order:[:month,:year])  %>
    <%= f.hidden_field :kasbon_id, :value => params[:id] %>
  </div>
  <div class="field">
    <%= f.label :jumlah_bayar %><br>
    <%= f.text_field :jumlah_bayar %>
  </div>
  <div class="actions">
    <%= f.submit "Simpan Pambayaran" %>
  </div>
<% end %>

app/views/detail_kasbons/edit.html.erb
<h1>Editing Detail Kasbon</h1>

<%= render 'form' %>

<%= link_to 'Show', @detail_kasbon %> |
<%= link_to 'Back', detail_kasbons_path %>

app/views/detail_kasbons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Detail Kasbons</h1>

<table>
  <thead>
    <tr>
      <th>Tanggal bayar</th>
      <th>Jumlah bayar</th>
      <th>Sisa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @detail_kasbons.each do |detail_kasbon| %>
      <tr>
        <td><%= detail_kasbon.tanggal_bayar %></td>
        <td><%= detail_kasbon.jumlah_bayar %></td>
        <td><%= detail_kasbon.sisa %></td>
        <td><%= link_to 'Show', detail_kasbon %></td>
        <td><%= link_to 'Edit', edit_detail_kasbon_path(detail_kasbon) %></td>
        <td><%= link_to 'Destroy', detail_kasbon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Detail kasbon', new_detail_kasbon_path %>

app/views/detail_kasbons/new.html.erb
<h1>New Detail Kasbon</h1>

<%= render 'form' %>

<%= link_to 'Back', detail_kasbons_path %>

app/views/detail_kasbons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tanggal bayar:</strong>
  <%= @detail_kasbon.tanggal_bayar %>
</p>

<p>
  <strong>Jumlah bayar:</strong>
  <%= @detail_kasbon.jumlah_bayar %>
</p>

<p>
  <strong>Sisa:</strong>
  <%= @detail_kasbon.sisa %>
</p>

<%= link_to 'Edit', edit_detail_kasbon_path(@detail_kasbon) %> |
<%= link_to 'Back', detail_kasbons_path %>