config/routes.rb
Rails.application.routes.draw do
  resources :detail_kasbons
  resources :potongan_employees
  resources :kasbons
  resources :potongans
  resources :golongans
  resources :take_homes
  resources :additional_incomes
  resources :salaries
  resources :attendances
  resources :group_rosters
  resources :rosters
  resources :restos
  resources :position_groups
  resources :locations
  resources :employees

  root 'welcome#index'
  get 'restos/:id/new' => 'restos#add_employee', as: :add_employee
  get 'employees/salary_recap/:month&:year' => 'employees#salary_recap', as: :salary_recap
  get 'golongans/:id/group_rosters' => 'golongans#roster_group', as: :roster_group
  get 'employees/:id/salary_detail/:month&:year' =>'employees#salary_detail', as: :salary_detail
  get 'employees/:id/tambah_income/:month&:year' =>'employees#tambah_income', as: :tambah_income
  get 'employees/:id/kasbon' => 'employees#kasbon', as: :employee_kasbon
  post 'employees/:id/add_row/:month&:year' => 'employees#add_row', as: :emp_add_income_row
  post 'employees/:id/add_potong/:month&:year' => 'employees#add_potong', as: :emp_add_potong_row
  

end

app/models/position_group.rb
class PositionGroup < ActiveRecord::Base
  belongs_to :golongan
  belongs_to :employee
  has_many :restos
end

app/controllers/position_groups_controller.rb
class PositionGroupsController < ApplicationController
  before_action :set_position_group, only: [:show, :edit, :update, :destroy]

  # GET /position_groups
  # GET /position_groups.json
  def index
    @position_groups = PositionGroup.all
  end

  # GET /position_groups/1
  # GET /position_groups/1.json
  def show
  end

  # GET /position_groups/new
  def new
    @position_group = PositionGroup.new
  end

  # GET /position_groups/1/edit
  def edit
  end

  # POST /position_groups
  # POST /position_groups.json
  def create
    @position_group = PositionGroup.new(position_group_params)

    respond_to do |format|
      if @position_group.save
        format.html { redirect_to @position_group, notice: 'Position group was successfully created.' }
        format.json { render :show, status: :created, location: @position_group }
      else
        format.html { render :new }
        format.json { render json: @position_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /position_groups/1
  # PATCH/PUT /position_groups/1.json
  def update
    respond_to do |format|
      if @position_group.update(position_group_params)
        format.html { redirect_to @position_group, notice: 'Position group was successfully updated.' }
        format.json { render :show, status: :ok, location: @position_group }
      else
        format.html { render :edit }
        format.json { render json: @position_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /position_groups/1
  # DELETE /position_groups/1.json
  def destroy
    @position_group.destroy
    respond_to do |format|
      format.html { redirect_to position_groups_url, notice: 'Position group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position_group
      @position_group = PositionGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_group_params
      params.require(:position_group).permit(:name, :note, :golongan_id)
    end
end

app/helpers/position_groups_helper.rb
module PositionGroupsHelper
end

app/views/position_groups/_form.html.erb
<%= form_for(@position_group) do |f| %>
  <% if @position_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position_group.errors.count, "error") %> prohibited this position_group from being saved:</h2>

      <ul>
      <% @position_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <!--<div class="field">-->
  <!--  <%= f.label :golongan_id %><br>-->
  <!--  <%= f.collection_select :golongan_id, Golongan.all.order(:nama), :id, :nama, prompt: true %>-->
  <!--</div>-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/position_groups/edit.html.erb
<div class="container">
  <nav class="navbar navbar-inverse">
    <p class="navbar-title">Edit Posisi</p>
  </nav>
</div><br>
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-lg-12">
        <div class="row">
            <%= render 'form' %>

       </div>
    </div>
  </div>
</div>

app/views/position_groups/index.html.erb
<div class="container">
  <nav class="navbar navbar-inverse">
    <p class="navbar-title">Posisi Karyawan</p>
  </nav>
</div><br>
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-lg-12">
          <div class="row">
            <%= link_to 'Tambah Posisi', new_position_group_path, class: 'btn btn-primary pull-right' %>
          </div><br>
          <div class="row">
            <div class="table-responsive">
              <table class="table table-bordered table-hover table-condensed">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Note</th>
                    <th colspan="3">Actions</th>
                  </tr>
                </thead>
              
                <tbody>
                  <% @position_groups.each do |position_group| %>
                    <tr>
                      <td><%= position_group.name %></td>
                      <td><%= position_group.note %></td>
                      <td align="center", width="15%">
                        <%= link_to  position_group  , class: 'btn btn-info' do %>
                          <i class="glyphicon glyphicon-eye-open"></i>
                        <% end %>
                        <%= link_to edit_position_group_path(position_group), class: 'btn btn-success' do%>
                          <i class="glyphicon glyphicon-edit"></i>
                        <% end %>
                        <%= link_to  position_group, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
                          <i class="glyphicon glyphicon-trash"></i>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
       </div>
    </div>
  </div>
</div>

app/views/position_groups/new.html.erb
<div class="container">
  <nav class="navbar navbar-inverse">
    <p class="navbar-title">Tambah Posisi</p>
  </nav>
</div><br>
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-lg-12">
        <div class="row">
            <%= render 'form' %>

       </div>
    </div>
  </div>
</div>

app/views/position_groups/show.html.erb
<div class="container">
  <nav class="navbar navbar-inverse">
    <p class="navbar-title"><%= @position_group.name %></p>
  </nav>
</div><br>
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-lg-12">
        <div class="row">
          <p>
            <strong>Name:</strong>
            <%= @position_group.name %>
          </p>
          
          <p>
            <strong>Note:</strong>
            <%= @position_group.note %>
          </p>
          
          <!--<p>-->
          <!--  <strong>Group:</strong>-->
          <!--  %= @position_group.golongan.nama %>-->
          <!--</p>-->
          
          <%= link_to 'Edit', edit_position_group_path(@position_group) %> |
          <%= link_to 'Back', position_groups_path %>
       </div>
    </div>
  </div>
</div>