config/routes.rb
Rails.application.routes.draw do
  resources :detail_kasbons
  resources :potongan_employees
  resources :kasbons
  resources :potongans
  resources :golongans
  resources :take_homes
  resources :additional_incomes
  resources :salaries
  resources :attendances
  resources :group_rosters
  resources :rosters
  resources :restos
  resources :position_groups
  resources :locations
  resources :employees

  root 'welcome#index'
  get 'restos/:id/new' => 'restos#add_employee', as: :add_employee
  get 'employees/salary_recap/:month&:year' => 'employees#salary_recap', as: :salary_recap
  get 'golongans/:id/group_rosters' => 'golongans#roster_group', as: :roster_group
  get 'employees/:id/salary_detail/:month&:year' =>'employees#salary_detail', as: :salary_detail
  get 'employees/:id/tambah_income/:month&:year' =>'employees#tambah_income', as: :tambah_income
  get 'employees/:id/kasbon' => 'employees#kasbon', as: :employee_kasbon
  post 'employees/:id/add_row/:month&:year' => 'employees#add_row', as: :emp_add_income_row
  post 'employees/:id/add_potong/:month&:year' => 'employees#add_potong', as: :emp_add_potong_row
  

end

app/models/salary.rb
class Salary < ActiveRecord::Base
  belongs_to :employee
  has_many :attendances
end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController
  before_action :set_salary, only: [:show, :edit, :update, :destroy]

  # GET /salaries
  # GET /salaries.json
  def index
    @salaries = Salary.all
  end

  # GET /salaries/1
  # GET /salaries/1.json
  def show
    @employee = @salary.employee_id
    @resto = Resto.find_by_employee_id(@employee)
    @attendances = Attendance.where('employee_id = ? AND att_month = ?', @employee, '2017-12-30')
    @total = 0.00
    @count = @attendances.sum(:day_count)
  end

  # GET /salaries/new
  def new
    @salary = Salary.new
  end

  # GET /salaries/1/edit
  def edit
  end

  # POST /salaries
  # POST /salaries.json
  def create
    @salary = Salary.new(salary_params)

    respond_to do |format|
      if @salary.save
        format.html { redirect_to @salary, notice: 'Salary was successfully created.' }
        format.json { render :show, status: :created, location: @salary }
      else
        format.html { render :new }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salaries/1
  # PATCH/PUT /salaries/1.json
  def update
    respond_to do |format|
      if @salary.update(salary_params)
        format.html { redirect_to @salary, notice: 'Salary was successfully updated.' }
        format.json { render :show, status: :ok, location: @salary }
      else
        format.html { render :edit }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salaries/1
  # DELETE /salaries/1.json
  def destroy
    @salary.destroy
    respond_to do |format|
      format.html { redirect_to salaries_url, notice: 'Salary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salary
      @salary = Salary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salary_params
      params.require(:salary).permit(:salary_period, :employee_id)
    end
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/views/salaries/_form.html.erb
<%= form_for(@salary) do |f| %>
  <% if @salary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@salary.errors.count, "error") %> prohibited this salary from being saved:</h2>

      <ul>
      <% @salary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :salary_period %><br>
    <%= f.date_select :salary_period %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.text_field :employee_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salaries/edit.html.erb
<h1>Editing Salary</h1>

<%= render 'form' %>

<%= link_to 'Show', @salary %> |
<%= link_to 'Back', salaries_path %>

app/views/salaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Salaries</h1>

<table>
  <thead>
    <tr>
      <th>Salary period</th>
      <th>Employee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salaries.each do |salary| %>
      <tr>
        <td><%= salary.salary_period %></td>
        <td><%= salary.employee.name %></td>
        <td><%= link_to 'Show', salary %></td>
        <td><%= link_to 'Edit', edit_salary_path(salary) %></td>
        <td><%= link_to 'Destroy', salary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Salary', new_salary_path %>

app/views/salaries/new.html.erb
<h1>New Salary</h1>

<%= render 'form' %>

<%= link_to 'Back', salaries_path %>

app/views/salaries/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <nav class="navbar navbar-inverse">
    <p class="navbar-title"><%= @resto.location.name %></p>
  </nav>
</div><br>
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-lg-12">
            <strong>Salary period:</strong>
            <%= @salary.salary_period.strftime("%B %Y") %>
      </div>
      <div class="col-lg-12">
            <strong>Tanggal Bayar:</strong>
            <%= "1 " + (@salary.salary_period + 1.month).strftime("%B %Y") %><br>
      </div>
    </div><br>
    <div class="row">
      <div class="col-lg-12">
            <strong>Employee:</strong>
            <%= @salary.employee.name %>
      </div>
      <div class="col-lg-12">
            <strong>Posisi:</strong>
            <%= @resto.position_group.name + " (" + @resto.position_group.group.name + ")"%>
      </div>
     </div><br>
    <div class="row">
      <div class="col-lg-9">    
            <strong>Gaji Pokok:</strong>
      </div>
      <div class="col-lg-1 text-right">    
        Rp.
      </div>
      <div class="col-lg-1 text-right">
            <%= delimiter(@resto.position_group.group.salary) %>
      </div>
    </div>
    <strong>Kehadiran</strong>
    <% @attendances.each do |att| %>
      <div class="row justify-content-start">
        <div class="col-lg-3">
          <%= att.group_roster.roster.hari + " " + att.group_roster.roster.detail %> 
        </div>
        <div class="col-lg-2">
          <div class="col-sm-1">
            Rp. 
          </div>
          <div class="col-sm-1">
            <%= delimiter(att.group_roster.amount) %>
          </div>
        </div>
        
        <div class="col-lg-2">
          <div class="col-sm-4">
            x 
          </div>
          <div class="col-sm-4 text-right">
            <%= att.day_count %>
          </div>
          <div class="col-lg-4">
            hari
          </div>
        </div>
        <div class="col-lg-1">
          = Rp. 
        </div>
        <div class="col-md-1 text-right">
          <%= delimiter(att.group_roster.amount * att.day_count) %>
        </div>
          <% @total = @total + att.group_roster.amount * att.day_count %>
        
      </div>
    <% end %>
    
    <div class="row justify-content-start">
        <div class="col-lg-3">
        </div>  
        <div class="col-lg-2 text-right">
            Total kehadiran :
        </div>
        <div class="col-lg-2">
          <div class="col-sm-4">
             
          </div>
          <div class="col-sm-4 text-right">
            <%= @count %>
          </div>
          <div class="col-lg-4">
            hari
          </div>
        </div>
        
      </div>
    
    
    <div class="row">
      <div class="col-lg-9">    
            <strong>Total :</strong>
      </div>
      <div class="col-lg-1 right-text">    
        Rp.
      </div>
      <div class="col-lg-1 right-text">
            <%= delimiter(@total) %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-9">    
            
      </div>
      <div class="col-lg-1 right-text">    
        Rp.
      </div>
      <div class="col-lg-1 right-text">
            <%= delimiter(@total + @resto.position_group.group.salary) %> 
      </div>
    </div>